### ISSUE TITLE
请教关于mongodb2.6的用户认证问题

### ISSUE THREAD

**Issue by mpdlink** [magicdict/MagicMongoDBTool#14]
能否发一个编译好能用的程序给我，我这边vs2010没导进去。。邮箱657414812@qq.com，非常感谢。
还有一个额外的问题想请教，如题，我的问题是mongodb官网给出的C#驱动貌似并没有对2.6版本的用户认证做出升级支持，我看了MagicMongoDBTool里面关于用户的代码，看起来你们的做法是直接操作用户表的内容然后保存的，那么我想知道用C#实现还有别的方法给非admin的数据库添加用户吗？
我测试安装一个新的mongodb2.6，然后我用runCommand方式createUser一个admin的超级用户赋予了对所有数据的管理，用户管理和读写权限，然后我再通过认证登陆admin数据库然后切换到一个新的数据库temp，然后我想给这个temp添加用户也通过runCommand方式结果总是报错，说我没有认证temp数据库没有权限操作。谢谢你们了。

**Comment by magicdict** [comment]
给你回复邮件了。
官方估计不准备改User类了，只能自己动手。
你所说的admin的问题，暂时没有时间去做测试。
